### PR TITLE
Update rules for 2016 Smallpeice game

### PR DESCRIPTION
**Pull request by prophile**
Game name is yet to be specified.

PDF:

[rules.pdf](https://github.com/prophile/smallpeice-rules/files/356156/rules.pdf)

### CODE REVIEW

**Comment by Adimote** [comment]
Would this game be adversely affected by having the 20cm-ish cubes we have in storage already?

**Comment by prophile** [comment]
@Adimote No, we could use them: are they coloured and numbered or plain cardboard boxes?

**Comment by Adimote** [comment]
@prophile Plain cardboard, we have about 90 of them sitting around. I will get the actual specifications. They are visibly not-cubes though (probably 20cm +/- 2cm)

**Comment by Adimote** [comment]
Have just measured the boxes, they are 25x26x25, so we can call it 250mm +/- 15mm

**Comment by Adimote** [comment]
Personally I'd prefer smaller boxes, it means teams might think up a bucket mechanism or something to carry more than 1

**Comment by Adimote** [comment]
Game name suggestion: Poison picker

**Comment by Adimote** [comment]
Giorgos pointed out that there may need to be markers in the podium on the centre, as otherwise it would be pretty hard to drive a robot to the centre of the arena.

**Comment by HarryCutts** [comment]
Regarding markers on the podium, we had one last year which was unmarked. A lot of people came to me asking how to detect it, and it added somewhat to the programming challenge. However, I don't remember many robots driving into it, so I guess they found decent solutions. I would think that putting markers on it would lead the competitors to assume that those markers would be visible, which is probably a bad assumption and so would lead to less robust programs.

**Comment by Adimote** [comment]
I don't think there's a specification of the width of the podium in the centre

**Comment by prophile** [comment]
Width of the podium specified in a9bc24f

**Pull request merged**
